### ISSUE TITLE
reportlab is not a MIT license (!)

### ISSUE THREAD

**Issue by andersfylling** [baruchel/txt2pdf#34]
> ## 1.3 Licensing
>
> The open-source version of the ReportLab toolkit and our other open-source tools are available under the BSD license. This means that you can basically do anything you want with it, including using it in a commercial package. (We used to use the Python license, but the Python license became historically complicated. We chose the BSD license because it was the shortest and most readable Open Source license).
>
> pyRXP, our XML parser, is under the GNU General Public License. This is because the RXP parser within it is under such a license. If you want to use pyRXP in a closed source project you will have to negotiate with us. rlextra, our commercial software package that contains pyRXPis also licensed. Pricing details can be found [here](https://www.reportlab.com/pricing).

https://docs.reportlab.com/developerfaqs/

**Comment by baruchel** [comment]
Hi, thank you for the info. I have not been maintaining this repository for years; however I gave some admin rights to other contributors which seem more interested than me in maintaining it. What do you suggest for solving the issue? Should I change the license?

**Comment by clach04** [comment]
@baruchel please hold off on making (and offering to make) licensing changes decisions until we have more details.

**Comment by clach04** [comment]
@andersfylling what outcome(s) are you hoping for?

Please explain why you think the pyRXP license is relevant here. This project does not (to my knowledge) use pyRXP. You can check the source code to confirm/deny this statement :-)

This project does make use of reportlab as a dependency (specifically older versions), this is the ONLY dependency, see https://github.com/baruchel/txt2pdf/blob/master/requirements.txt

From Version 3.6.1 of reportlab setup.py, downloaded from https://pypi.org/project/reportlab/3.6.1/#files :

```
....
            install_requires=['pillow>=4.0.0'],
            python_requires='>=2.7, >=3.6, <4',
            extras_require={
                'RLPYCAIRO': ['rlPyCairo>=0.0.5'],
                },
            )
....
```

Pillow (11.0.0) does not depend on pyRXP. 

txt2pdf does NOT make use of extras.

End users might choose to deploy additional libraries, like pyRXP which reportlab will import if available. I can not comment on its usage as this project txt2pdf does make make use of this, potentially a question for ReportLab Inc.

In addition https://pypi.org/project/reportlab/3.6.1/#files clearly is marked as BSD (same for setup.py), if you feel this is in error this may be appropriate to discuss with ReportLab Inc. We are in good faith interpreting this as BSD as the license has been BSD since 2006 https://pypi.org/project/reportlab/2.0/

txt2pdf is not a closed source product.

@baruchel I recommend we close this if there are no responses in 14 days.

**Comment by andersfylling** [comment]
Seems i included an extra paragraph there. Reportlab is BSD which is different from MIT, so to avoid confusion I'd suggest inheriting that license unless there are some conditions I'm not familiar with(?).

And yes no need to rush a change, but it's good to get this right just to avoid potential headaches.

**Comment by clach04** [comment]
@andersfylling If you feel/think/have-evidence that suggest that txt2pdf is in anyway incompatible with reportlab please make that clear. I see no confusion in the licensing of txt2pdf nor reportlab. The txt2pdf license is less than 10 lines and the license.txt with reportlab is less than 30, they are deliberately short and easy reads.

This project, https://github.com/baruchel/txt2pdf is **NOT** distributing reportlab, which would be the point at which this project would need to even make reference to the license reportlab is available under. If this project did do that, it would be fully compliant and compatible. https://libguides.wvu.edu/c.php?g=1260463&p=9239129#:~:text=The%20BSD%20Family%20of%20licenses%20are%20highly%20compatible%20the%20BSD,GNU%2DGPL%20family%20of%20license. is a fairly clear/easy read if you are looking for another opinion.

If you have specific concerns or grievances, please document them clearly with reference to the section(s) of the license in question.

It feels like you want to help, but I'm not clear there is anything to help out with here.

If you are shipping distributions txt2pdf (with dependencies) you need to be clear on your responsibilities (and rights). If you don't like the license, you don't have to use this software (nor reportlab) 😉

**Comment by andersfylling** [comment]
Isn't it installed when I install your software? If i go in and see a MIT license I wouldnt axpect it to secretly have BSD license included, via some legal loophole

**Comment by clach04** [comment]
> Isn't it installed when I install your software? If i go in and see a MIT license I wouldnt axpect it to secretly have BSD license included, via some legal loophole

I can't tell if you genuinely don't understand, trolling, or attempting to convert the license for reasons unknown.

I've asked you multiple times for specifics and at no point have you responded with such. If your most recent question is legitimate then this is the wrong place to ask it. Consult a lawyer.

Closing.
